// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type Post struct {
	ID          *string `json:"id"`
	Createdat   *int    `json:"createdat"`
	Updatedat   *int    `json:"updatedat"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Markdown    *string `json:"markdown"`
}
